set signals [list]

lappend signals "clock"
lappend signals "serial_rx"
lappend signals "serial_tx"
lappend signals "dut.reset"
lappend signals "dut.addr"
lappend signals "dut.data_out"
lappend signals "dut.data_in"
lappend signals "dut.ack"
lappend signals "dut.cyc"
lappend signals "dut.we"
lappend signals "dut.strobe"
lappend signals "dut.wb_master.rx_ready"
lappend signals "dut.wb_master.rx_valid"
lappend signals "dut.wb_master.rx_byte_consumed"
lappend signals "dut.wb_master.tx_ready"
lappend signals "dut.wb_master.tx_valid"
lappend signals "dut.wb_master.tx_byte"
lappend signals "dut.wb_master.uart0.tx_shift"
lappend signals "dut.wb_master.p_state"
lappend signals "dut.wb_master.p_next"
lappend signals "dut.wb_master.rq_addr"
lappend signals "dut.wb_master.rq_addr_next"
lappend signals "dut.wb_master.word_count"
lappend signals "dut.wb_master.word_count_next"
lappend signals "dut.wb_regs.\\registers\[0\]\[31:0\]"
lappend signals "dut.wb_regs.\\registers\[1\]\[31:0\]"

set signal_count [ gtkwave::addSignalsFromList $signals ]
